### ISSUE TITLE
CDC Criteria 1A logic

### ISSUE THREAD

**Issue by Unponderable** [usdigitalresponse/covid-exit-strategy#49]
In inspecting the methodology of covid/transform.py, I noticed that Criteria 1A is caclulated based on the function calculate_max_run_in_window(), implying that you need at least 9 consecutive days of decreases to meet this criteria.  However, this appears to be inconsistent with the CDC provisions allowing for the "grace period" of no more than 5 days.

For example, if in a 14-day window, I have 7 day of consecutive decreases, followed by 1 day of increase, followed by 6 more days of consecutive decreases, this would appear to fail criteria 1A as coded since the "max run" would be 7.  

The CDC guidance isn't super clear here but I'm not sure this is the intention.  I think the intention, to be logically consistent with the grace period allowance, would be to calculate 1A with the _total_ number of daily decreases in a 14-day window, and not the "max run".  That would allow the hypothetical example above to pass criteria 1A, whereas right now it would fail as coded.

I'm not a Python coder, so pardon me if I miss something otherwise obvious.

**Comment by patricksheehan** [comment]
@Unponderable Thanks for bringing this to our attention! I'll loop in the dev who contributed that criteria, we'll double-check the code against the CDC guideline and report back. If you're indeed correct, we'll update our logic and add a test to verify.

**Comment by lucasmbrown** [comment]
Hi @Unponderable -- thanks so much for your interest and taking the time to write in this question. You raise a great question that honestly we debated for a bit internally as we were implementing these measures. It’s a very astute point to raise! 

Your interpretation of how we’ve implemented these measures is exactly right. And you’re also right that the guidance is not as explicit as it could be on these topics. 

The section we paid particular attention to in the CDC’s documents is: 

> A period of 14 days of declining cases occurs when fewer cases are reported at the end of the 14 days compared with the number at the beginning of the period, using the 3-day rolling average fitted with the spline curve to define the number of cases. In addition, a “grace period” of 5 days may be applied during a downward trajectory, during which cases may increase for no more than 5 consecutive days.

And, repeated: 

> 14 consecutive days of decline required but can use up to a 5-day grace period if data are inconsistent

We started by knowing the goal of the criteria is to indicate that there’s been a 14 day consecutive decline, correcting for a little bit of noise. Note that this is being applied to a data series that is already quite smoothed, because it’s been converted into a three-day rolling average and had a cubic spline smoother applied on top of it. So any increases in this trend are pretty significant, since they’re not one-off blips. 

We considered implementing the calculation as allowing up to five positive days throughout the 14 day window. For instance, in that scenario, the following data would qualify as a 14 day decline: 

1. -1
2. -1
3. 4
4. -1
5. -1
6. 5
7. -1
8. 3
9. -1
10. 5
11. -1
12. 7
13. -1
14. -1

Note this data would qualify as a 14-day consecutive decline even though in reality, on an already doubly-smoothed trend, the data never has more than 2 days of consecutive decline. Since we know we’re trying to “actually” reach a 14 day window after adjusting for a small amount of noise, it doesn’t seem right to declare the above as meeting that criteria. 

We also feel like this meets the CDC’s guidance more accurately -- since they say “a” grace period may be applied during “a” downward trajectory, rather than allowing for many grace periods. 

Let us know if you see anything else worth flagging in the repository -- we’re very thankful for your feedback and insights!

**Comment by lucasmbrown** [comment]
Closing this for now since it's been inactive for a couple weeks; @Unponderable let us know if you have any further questions or comments!

**Comment by Unponderable** [comment]
Thanks for reminding me.  I see the logic in the decision made and I can't argue that either choice is perfect.  I'll move on to wondering why the CDC's guidance is trend-based with minimal consideration of the overall magnitude of case rate. 😅 

I didn't say it in my original post but thank you all very much for the work you've done here.  This site has been very valuable to me in the last few months.  The reason I was scrutinizing the logic is that I was writing a spreadsheet to do the same analysis for individual county-by-county case data - the ones published on USAFacts.org.  It works pretty well if you have large enough populations in your counties, or you lump neighboring counties together.
